### ISSUE TITLE
Work on models

### ISSUE THREAD

**Issue by Thooms** [Atilla106/shop.eistiens.net#1]
* https://github.com/Atilla106/shop.eistiens.net/blob/master/shop/models.py is already here, but a validation can't hurt
* Some permissions might by missing

**Comment by MrChoclate** [comment]
Where do we add Braintree's keys?
Do we use one account or every association has a key?

**Comment by Thooms** [comment]
A key per association seems like a good design, let's store it in the model (some kind of `CharField` will do it). This way we let the associations handle their keys, and we just use them.
