### ISSUE TITLE
Index template is not rendering

### ISSUE THREAD

**Issue by MrChoclate** [Atilla106/shop.eistiens.net#10]
NoReverseMatch at /
Reverse for 'asso_shop' with arguments '('Asso1',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['(?P<association_name>[a-zA-Z]+)/$']

@Thooms Please add dummy functionnal test

**Comment by Thooms** [comment]
https://github.com/Atilla106/shop.eistiens.net/pull/12
