### ISSUE TITLE
Use of generic views

### ISSUE THREAD

**Issue by florent1933** [Atilla106/shop.eistiens.net#13]
I think it's better to use generic views like ListView : https://docs.djangoproject.com/en/1.8/topics/class-based-views/generic-display/#generic-views-of-objects

Example of code which can be refactor with ListView
```
def home(request):
    """
    Homepage
    """
    associations = Association.objects.all()
    context = {
        'associations': associations,
        'title': 'HOME'
    }
    return render(request, 'shop/home.html', context)
```

:+1: 

```
class AssociationList(ListView):
    """
    Homepage
    """
    model = associations
```

**Comment by florent1933** [comment]
It's also possible to replace
```
def asso_shop(request, association_name):
    """
    Displays the association's shop.
    Will only displays available items for the user.
    """
    pass
```

by 

```
class AssociationDetail(DetailView):
    """
    Homepage
    """
    model = associations
```

And to display if it's a manager, it's possible to add an extra context

**Comment by Thooms** [comment]
Hm, I'll think about it. In my mind we'd loose flexilbility by doing this, but in the other hand it's less unit tests :D
