### ISSUE TITLE
Misunderstanding of add_associations() in context_processors.py

### ISSUE THREAD

**Issue by florent1933** [Atilla106/shop.eistiens.net#15]
I don't understand why it's in the code, it's not use in the settings.

```
...
                'django.core.context_processors.request',

                #'shop.context_processors.add_associations',
            ],
```

I need help to understand this function. What is the purpose ? Why a context ?

Why only one product ? => .get 
```
Product.objects.get(owner=asso)
```

**Comment by Thooms** [comment]
Hm, I'll fix that.

**Comment by florent1933** [comment]
When it will be fixed?
