### ISSUE TITLE
Abandonned project?

### ISSUE THREAD

**Issue by florent1933** [Atilla106/shop.eistiens.net#17]

**Comment by Wonscalb** [comment]
I don't think so. But it might be better to build it in conjunction with the new platform

**Comment by MrChoclate** [comment]
The new platform being eistiens.net v3?

**Comment by Wonscalb** [comment]
Yep
Le 6 mars 2016 2:02 PM, "Clément VILLAIN" <notifications@github.com> a
écrit :

> The new platform being eistiens.net v3?
