### ISSUE TITLE
[User story] Have tickets handling

### ISSUE THREAD

**Issue by Thooms** [Atilla106/shop.eistiens.net#5]
An admin should be able to define specific products know as tickets, that are uniquely numbered/labelled, and
nomitative or not. He should also be able to have a list of successful transactions on this product (== tickets sold), with the relevant infos (ticket number, name, ...).

Bonus level: have a PDF ticket generator, so that a user buying one can print it (QR code ?)

Bonus level 2: have an API endpoint to validate a ticket (could be used in party entrance)

**Comment by MrChoclate** [comment]
A ticket number could be link to a user via ldap login or employeeNumber. (How to sell to non-eisti members?)
API endpoint should not be a bonus ;)

**Comment by Thooms** [comment]
OK for the API, let's spec it correctly :) I don't think linking to the LDAP here is a good idea, let's instead use shop.eistiens.net's User profiles. We don't lose the possibility of getting the LDAP entry for a User, and we're not stuck for external users.
