### ISSUE TITLE
[User story] Transaction status

### ISSUE THREAD

**Issue by Thooms** [Atilla106/shop.eistiens.net#6]
A user, and an admin should be able to visualize a given transaction status.

**Comment by MrChoclate** [comment]
Transaction should only be validated? I do not understand.
A user buy a product from an association. We do not support after-sales service or delivery information.

**Comment by Thooms** [comment]
I'm just talking about being able to see in what stage is a transaction (paid, waiting for ca$h, product ready to be fetched, ...). This way a user can check that everything is going well, and an admin can have a global overview on his shop.
