### ISSUE TITLE
Write tests for everything and make sure incorrect/incomplete testing doesn't pass CI.

### ISSUE THREAD

**Issue by Thooms** [Atilla106/shop.eistiens.net#9]
There's almost no code right now, let's have 100% coverage and 100% lint score before starting to iterate <3

**Comment by MrChoclate** [comment]
How do get your metric? Add it on readme?

**Comment by Thooms** [comment]
This part is covered (pun intended <3 ) by the testsuite (https://github.com/Atilla106/shop.eistiens.net/blob/master/eisti_shop/settings.py#L122-L130) and test script (https://github.com/Atilla106/shop.eistiens.net/blob/master/flake8.sh) that ended up in the CI

**Comment by Thooms** [comment]
Though it could be relevant to be sure that a incorrectly linted code make the CI tests fails. I'll do it.

**Comment by MrChoclate** [comment]
> Though it could be relevant to be sure that a incorrectly linted code make the CI tests fails. I'll do it.
flake8 is part of the tests ?

**Comment by Thooms** [comment]
I understand "CI tests" as "all the tests run by the CI", then yes, lint tests like flake8 are part of it (according to me, at least). What do you think?
